name: "ARK Nitrado Discord Bot"
version: "1.0.1"
slug: "ark_nitrado_discord_bot"
description: "Discord bot to start/stop and check status of a Nitrado ARK server"
startup: services
boot: auto
init: false
map:
  - config:ro
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
options:
  discord_bot_token: ""
  discord_bot_token_file: ""
  discord_guild_id: ""
  nitrado_token: ""
  nitrado_token_file: ""
  nitrado_service_id: ""
  status_channel_id: ""
  status_update_interval_minutes: 10
schema:
  discord_bot_token: "password?"
  discord_bot_token_file: "str?"
  discord_guild_id: str
  nitrado_token: "password?"
  nitrado_token_file: "str?"
  nitrado_service_id: str
  status_channel_id: "str?"
  status_update_interval_minutes: int(1,120)
